### ISSUE TITLE
IgrDataGrid collapses its records when there are many columns and a FilterRow present

### ISSUE THREAD

**Issue by agoldenbaum** [IgniteUI/igniteui-react#19]
**Steps to Reproduce:**
1. Run the attached sample project.
2. Scroll the grid horizontally.

**Result:**
The grid collapses all of its records after scrolling about halfway to the max horizontal scroll value.

**Expected:**
Grid should not collapse its rows

[demo-2.zip](https://github.com/IgniteUI/igniteui-react/files/11235976/demo-2.zip)

**Comment by ig-robstoffers** [comment]
This issue should get resolved in the next version update. It stemmed from a bug where boolean columns were applying a filter immediately when the filter cell came into view. As you scrolled horizontally you uncovered a new boolean column that had all `false` values but the column auto-created a `value == true` filter which filtered all the rows out.

The behavior has been changed now so that by default a filter will not be created until the user actually picks `True` or `False` from the operator select menu, or types in a value for the `Equals` operator.

**Comment by cacode-euan** [comment]
@ig-robstoffers Great thank you for the update, 
do you know when the next version is due to be released?

**Comment by cacode-euan** [comment]
This appears to have been resolved in version 18.2.0
