### ISSUE TITLE
Cannot set value of date picker to undefined

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-react#69]
## Description  
I have a date picker bound to a variable. I am trying to delete its value by clicking on delete button.

## Steps to reproduce  
Setup the date picker like this:
```tsx
<IgrDatePicker value={date} selectedValueChanged={(_s, e) => setDate(e.newValue)} label="Date"></IgrDatePicker>
```
Select a date in the picker and then delete it via click on delete button (the x next to the calendar icon).

## Result  
The value of the picker becomes 01/01/0001.

## Expected result  
The value should become `undefined` or `null`.

**Comment by wnvko** [comment]
Same issue is valid for the calendar!

**Comment by MayaKirova** [comment]
@wnvko It seems that that is the default behavior of the igcDatePicker. If you delete the value and then check the property it seems to return Mon Jan 01 0001:
![image](https://github.com/IgniteUI/igniteui-react/assets/10397980/e2d22098-d3fb-4edb-b00e-56fd91673379)
The IgrDatePicker does the same since it simply wraps the IgcDatePicker. 

Perhaps this should be logged here to be fixed in the igc component: https://github.com/IgniteUI/igniteui-webcomponents/issues

**Comment by damyanpetev** [comment]
That'd be the old date picker then, it's replacement is imminent but not out just yet https://github.com/IgniteUI/igniteui-webcomponents/pull/1086. Not sure if an issue for the old will be prioritized at this point.
The other bit that irks me still the comment about the calendar, since this time the WC component accepts it and clears just fine:
![image](https://github.com/IgniteUI/igniteui-react/assets/3198469/f3cb7f23-f690-4229-b974-78c20a193f36)
If that's not the case in React there might still be an issue somewhere.

**Comment by MayaKirova** [comment]
@damyanpetev @wnvko  As far as I can tell the calendar doesn't have an issue with `undefined` as a value. It clears correctly and when checking the value it return undefined as expected: https://codesandbox.io/p/sandbox/fervent-borg-7n5fsh
Let me know if I'm missing something.
